spin_manifest_version = 2

[application]
name = "openai-proxy"
version = "0.1.0"
authors = ["Peter Salomonsen <pjsalomonsen@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "openai-proxy"

[component.openai-proxy]
source = "target/wasm32-wasi/release/openai_proxy.wasm"
allowed_outbound_hosts = ["https://api.openai.com:443"]
[component.openai-proxy.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[variables]
openai_api_key = { required = true }

[component.openai-proxy.variables]
openai_api_key = "{{ openai_api_key }}"