name: "Wasi preview 2 tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install spin
        run: |
          curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash
      - name: Build project
        working-directory: wasip2
        run: |
          spin build
      - name: Run tests
        working-directory: wasip2
        run: |
          spin test
        
          
      
          