name: "Wasi preview 2 tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash
          sudo mv spin /usr/local/bin/
          rustup target add wasm32-wasi
          spin plugin install -y -u https://github.com/fermyon/spin-test/releases/download/canary/spin-test.json
      - name: Build project
        working-directory: wasip2
        run: |
          spin build
      - name: Run tests
        working-directory: wasip2
        run: |
          spin test
        
          
      
          